consumes:
  - application/json
definitions:
  BaseRes:
    type: object
    properties:
      code:
        type: integer
      codeMsg:
        type: string
      msg:
        type: string
  Fund:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      code:
        type: string
  FundData:
    type: object
    properties:
      code:
        type: integer
      codeMsg:
        type: string
      data:
        $ref: "#/definitions/Fund"
      msg:
        type: string
  FundList:
    type: object
    properties:
      code:
        type: integer
      codeMsg:
        type: string
      list:
        type: array
        items:
          $ref: "#/definitions/Fund"
      msg:
        type: string
info:
  description: Life assistant api
  title: Docs
  version: 0.1.0
paths:
  /fund/createFund:
    post:
      tags:
        - fund
      summary: Create new fund
      parameters:
        - name: body
          in: body
          description: Fund object that needs to be created
          required: true
          schema:
            $ref: "#/definitions/Fund"
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/BaseRes"
  /fund/deleteFund:
    delete:
      tags:
        - fund
      summary: Delete fund by ID
      parameters:
        - name: id
          in: query
          description: id of fund to delete
          required: true
          type: integer
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/BaseRes"
  /fund/updateFund:
    patch:
      tags:
        - fund
      summary: Update  fund
      parameters:
        - name: body
          in: body
          description: Fund object that needs to be created
          required: true
          schema:
            $ref: "#/definitions/Fund"
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/BaseRes"
  /fund/getFund:
    get:
      tags:
        - fund
      summary: Find fund by ID
      parameters:
        - name: id
          in: query
          description: id of fund to return
          required: true
          type: integer
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/FundData"
  /fund/getFunds:
    get:
      tags:
        - fund
      summary: Find funds by fund object
      parameters:
        - name: code
          in: query
          description: code of fund to return
          type: string
        - name: name
          in: query
          description: name of fund to return
          type: string
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/FundList"
produces:
  - application/json
schemes:
  - http
swagger: "2.0"
