consumes:
  - application/json
definitions:
  BaseRes:
    type: object
    properties:
      code:
        type: integer
      codeMsg:
        type: string
      msg:
        type: string
  Fund:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      code:
        type: string
  FundData:
    type: object
    properties:
      code:
        type: integer
      codeMsg:
        type: string
      data:
        $ref: "#/definitions/Fund"
      msg:
        type: string
  FundList:
    type: object
    properties:
      code:
        type: integer
      codeMsg:
        type: string
      list:
        type: array
        items:
          $ref: "#/definitions/Fund"
      msg:
        type: string
      pageNo:
        type: integer
      pageSize:
        type: integer
      total:
        type: integer
  Order:
    type: object
    properties:
      orderNo:
        type: string
      code:
        type: string
      holdingDays:
        type: integer
      status:
        type: integer
      amount:
        type: string
      unitCost:
        type: string
      costPrice:
        type: string
  OrderData:
    type: object
    properties:
      code:
        type: integer
      codeMsg:
        type: string
      data:
        $ref: "#/definitions/Order"
      msg:
        type: string
  OrderList:
    type: object
    properties:
      code:
        type: integer
      codeMsg:
        type: string
      list:
        type: array
        items:
          $ref: "#/definitions/Order"
      msg:
        type: string
      pageNo:
        type: integer
      pageSize:
        type: integer
      total:
        type: integer
  Tag:
    type: object
    properties:
      name:
        type: string
      type:
        type: integer
  TagData:
    type: object
    properties:
      code:
        type: integer
      codeMsg:
        type: string
      data:
        $ref: "#/definitions/Tag"
      msg:
        type: string
  TagList:
    type: object
    properties:
      code:
        type: integer
      codeMsg:
        type: string
      list:
        type: array
        items:
          $ref: "#/definitions/Tag"
      msg:
        type: string
      pageNo:
        type: integer
      pageSize:
        type: integer
      total:
        type: integer
info:
  description: Life assistant api
  title: Docs
  version: 0.1.0
paths:
  /funds:
    post:
      tags:
        - fund
      summary: Create new fund
      parameters:
        - name: body
          in: body
          description: Fund object that needs to be created
          required: true
          schema:
            $ref: "#/definitions/Fund"
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/BaseRes"
    get:
      tags:
        - fund
      summary: Find funds by fund object
      parameters:
        - name: code
          in: query
          description: code of fund to return
          type: string
        - name: name
          in: query
          description: name of fund to return
          type: string
        - name: pageNo
          in: query
          description: pageNo of tag to return
          type: integer
        - name: pageSize
          in: query
          description: pageSize fo tag to return
          type: integer
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/FundList"
  /funds/{id}:
    delete:
      tags:
        - fund
      summary: Delete fund by ID
      parameters:
        - name: id
          in: path
          description: id of fund to delete
          required: true
          type: integer
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/BaseRes"
    get:
      tags:
        - fund
      summary: Find fund by ID
      parameters:
        - name: id
          in: path
          description: id of fund to return
          required: true
          type: integer
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/FundData"
    patch:
      tags:
        - fund
      summary: Update  fund
      parameters:
        - name: id
          in: path
          description: id of fund to return
          required: true
          type: integer
        - name: body
          in: body
          description: Fund object that needs to be created
          required: true
          schema:
            $ref: "#/definitions/Fund"
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/BaseRes"
  /funds/crawlWorth:
    post:
      tags:
        - fund
      summary: Crawl worths by fund code
      parameters:
        - name: code
          in: query
          description: code of fund to return
          type: string
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/BaseRes"
  /orders:
    post:
      tags:
        - order
      summary: Create new order
      parameters:
        - name: body
          in: body
          description: Order object that needs to be created
          required: true
          schema:
            $ref: "#/definitions/Order"
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/BaseRes"
    get:
      tags:
        - order
      summary: Find orders by fund object
      parameters:
        - name: code
          in: query
          description: code of order to return
          type: string
        - name: status
          in: query
          description: status of order to return
          type: string
        - name: amount
          in: query
          description: amount of order to return
          type: string
        - name: unitCost
          in: query
          description: unitCost of order to return
          type: string
        - name: orderTime
          in: query
          description: orderTime of order to return
          type: string
        - name: pageNo
          in: query
          description: pageNo of tag to return
          type: integer
        - name: pageSize
          in: query
          description: pageSize fo tag to return
          type: integer
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/OrderList"
  /orders/{id}:
    delete:
      tags:
        - order
      summary: Delete order by ID
      parameters:
        - name: id
          in: path
          description: id of order to delete
          required: true
          type: integer
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/BaseRes"
    get:
      tags:
        - order
      summary: Find order by ID
      parameters:
        - name: id
          in: path
          description: id of order to return
          required: true
          type: integer
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/OrderData"
    patch:
      tags:
        - order
      summary: Update order
      parameters:
        - name: id
          in: path
          description: id of order to return
          required: true
          type: integer
        - name: body
          in: body
          description: Order object that needs to be created
          required: true
          schema:
            $ref: "#/definitions/Order"
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/BaseRes"
  /tags:
    post:
      tags:
        - tag
      summary: Create new tag
      parameters:
        - name: body
          in: body
          description: Tag object that needs to be created
          required: true
          schema:
            $ref: "#/definitions/Tag"
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/BaseRes"
    get:
      tags:
        - tag
      summary: Find tags by fund object
      parameters:
        - name: name
          in: query
          description: name of tag to return
          type: string
        - name: type
          in: query
          description: type of tag to return
          type: integer
        - name: pageNo
          in: query
          description: pageNo of tag to return
          type: integer
        - name: pageSize
          in: query
          description: pageSize fo tag to return
          type: integer
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/TagList"
  /tags/{id}:
    delete:
      tags:
        - tag
      summary: Delete tag by ID
      parameters:
        - name: id
          in: path
          description: id of tag to delete
          required: true
          type: integer
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/BaseRes"
    get:
      tags:
        - tag
      summary: Find tag by ID
      parameters:
        - name: id
          in: path
          description: id of tag to return
          required: true
          type: integer
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/OrderData"
    patch:
      tags:
        - tag
      summary: Update tag
      parameters:
        - name: id
          in: path
          description: id of tag to return
          required: true
          type: integer
        - name: body
          in: body
          description: Tag object that needs to be updated
          required: true
          schema:
            $ref: "#/definitions/Tag"
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/BaseRes"
produces:
  - application/json
schemes:
  - http
swagger: "2.0"
