consumes:
  - application/json
definitions: {}
info:
  description: Life assistant api
  title: Docs
  version: 0.1.0
paths:
  /getFund:
    get:
      tags:
        - fund
      response: 200
produces:
  - application/json
schemes:
  - http
swagger: "2.0"
